### ISSUE TITLE
When replication is configured with a password, Sentinel is unable to monitor replication correctly.

### ISSUE THREAD

**Issue by elrondwong** [OT-CONTAINER-KIT/redis-operator#725] opened 2023-12-12 10:01 UTC
```conf
bash-5.1$ cat /etc/redis/sentinel.conf
port 26379
daemonize no
pidfile "/var/run/redis-sentinel.pid"
logfile ""
dir "/tmp"

acllog-max-len 128

# sentinel monitor mymaster 127.0.0.1 6379 2
# sentinel down-after-milliseconds mymaster 30000
# sentinel parallel-syncs mymaster 1
# sentinel failover-timeout mymaster 180000
sentinel deny-scripts-reconfig yes
sentinel resolve-hostnames no
sentinel announce-hostnames no
# SENTINEL master-reboot-down-after-period mymaster 0
protected-mode no
sentinel monitor myMaster 10.222.1.78 6379 2

# Generated by CONFIG REWRITE
latency-tracking-info-percentiles 50 99 99.9
user default on nopass sanitize-payload ~* &* +@all
sentinel myid d4d4a7e8b871e03c91c3ac9bf7ede917c89f0cb1
sentinel config-epoch myMaster 0
sentinel leader-epoch myMaster 0
sentinel current-epoch 0
```

**Comment by shubham-cmyk** [comment] 2023-12-18 06:41
Fixed you can use the `[additionalSentinelConfig](https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/tests/e2e-chainsaw/v1beta2/ha-setup/secured/partially-secured/replication-password/sentinel.yaml#L14)`  as done. 

but here the problem is you have to provide the Password in the configmap. 
I Have merged your PR that seems to be better approach also I would write explicit option to provide password and ACL option here.

**Closed** 2023-12-18 09:49 UTC
Labels: bug
