### ISSUE TITLE
PV claims are not released 

### ISSUE THREAD

**Issue by raghuiisc** [OT-CONTAINER-KIT/redis-operator#78] opened 2021-05-23 15:33 UTC
Steps followed as below. 

root@rkota-k8s-1:~/redis-operator/helm-charts# helm upgrade redis-cluster ./charts/redis-setup/ --set setupMode="cluster" --set cluster.size=3 --set "containerSecurityContext.runAsUser=0" --set "persistence.size=1Gi" --set "persistence.storageClass=local-storage" --install --namespace redis-operator
Release "redis-cluster" does not exist. Installing it now.
NAME: redis-cluster
LAST DEPLOYED: Sat May 22 17:42:38 2021
NAMESPACE: redis-operator
STATUS: deployed
REVISION: 1
TEST SUITE: None

root@rkota-k8s-1:~/redis-operator/helm-charts# kubectl get pods -A
NAMESPACE        NAME                                  READY   STATUS    RESTARTS   AGE
kube-system      coredns-558bd4d5db-jr889              1/1     Running   0          14m
kube-system      coredns-558bd4d5db-xgjsr              1/1     Running   0          14m
kube-system      etcd-rkota-k8s-1                      1/1     Running   0          14m
kube-system      kube-apiserver-rkota-k8s-1            1/1     Running   0          14m
kube-system      kube-controller-manager-rkota-k8s-1   1/1     Running   0          14m
kube-system      kube-proxy-7bk6k                      1/1     Running   0          14m
kube-system      kube-proxy-9rxd2                      1/1     Running   0          10m
kube-system      kube-scheduler-rkota-k8s-1            1/1     Running   0          14m
kube-system      weave-net-55xnf                       2/2     Running   0          10m
kube-system      weave-net-sv6cv                       2/2     Running   0          12m
redis-operator   redis-master-0                        2/2     Running   0          2m21s
redis-operator   redis-master-1                        2/2     Running   0          80s
redis-operator   redis-master-2                        2/2     Running   0          48s
redis-operator   redis-operator-78c558545b-7hs99       1/1     Running   0          6m55s
redis-operator   redis-slave-0                         2/2     Running   0          2m21s
redis-operator   redis-slave-1                         2/2     Running   0          79s
redis-operator   redis-slave-2                         2/2     Running   0          47s

root@rkota-k8s-1:~/redis-operator/helm-charts# kubectl get pv
NAME           CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                                        STORAGECLASS    REASON   AGE
pv-operator1   1Gi        RWO            Retain           Available                                                local-storage            7m48s
pv-operator2   1Gi        RWO            Retain           Bound       redis-operator/redis-master-redis-master-1   local-storage            7m48s
pv-operator3   1Gi        RWO            Retain           Bound       redis-operator/redis-slave-redis-slave-1     local-storage            7m48s
pv-operator4   1Gi        RWO            Retain           Bound       redis-operator/redis-master-redis-master-2   local-storage            7m48s
pv-operator5   1Gi        RWO            Retain           Bound       redis-operator/redis-slave-redis-slave-0     local-storage            7m48s
pv-operator6   1Gi        RWO            Retain           Bound       redis-operator/redis-slave-redis-slave-2     local-storage            7m48s
pv-operator7   1Gi        RWO            Retain           Available                                                local-storage            7m48s
pv-operator8   1Gi        RWO            Retain           Bound       redis-operator/redis-master-redis-master-0   local-storage            7m48s

Issue 1 : Redis-cluster is not formed.
ot@rkota-k8s-1:~/redis-operator/helm-charts# kubectl exec -it redis-master-0 -n redis-operator -- redis-cli -a Opstree@1234 cluster nodes
Defaulted container "redis-master" out of: redis-master, redis-exporter
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
2522ac30737df9a52463ad6a0a1cc3a36633a728 10.240.1.3:6379@16379 myself,master - 0 0 0 connected
root@rkota-k8s-1:~/redis-operator/helm-charts# kubectl exec -it redis-master-0 -n redis-operator -- redis-cli -a Opstree@1234 cluster nodes
Defaulted container "redis-master" out of: redis-master, redis-exporter
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
2522ac30737df9a52463ad6a0a1cc3a36633a728 10.240.1.3:6379@16379 myself,master - 0 0 0 connected
root@rkota-k8s-1:~/redis-operator/helm-charts# kubectl exec -it redis-master-0 -n redis-operator -- redis-cli -a Opstree@1234 cluster nodes
Defaulted container "redis-master" out of: redis-master, redis-exporter
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
2522ac30737df9a52463ad6a0a1cc3a36633a728 10.240.1.3:6379@16379 myself,master - 0 0 0 connected

later i delete the redis-cluster as below
root@rkota-k8s-1:~/redis-operator/helm-charts# helm delete redis-cluster --namespace redis-operator                                                                 release "redis-cluster" uninstalled

But PV claims are not released
root@rkota-k8s-1:~/redis-operator/helm-charts# kubectl get pods -A
NAMESPACE        NAME                                  READY   STATUS    RESTARTS   AGE
kube-system      coredns-558bd4d5db-jr889              1/1     Running   0          21h
kube-system      coredns-558bd4d5db-xgjsr              1/1     Running   0          21h
kube-system      etcd-rkota-k8s-1                      1/1     Running   0          21h
kube-system      kube-apiserver-rkota-k8s-1            1/1     Running   0          21h
kube-system      kube-controller-manager-rkota-k8s-1   1/1     Running   0          21h
kube-system      kube-proxy-7bk6k                      1/1     Running   0          21h
kube-system      kube-proxy-9rxd2                      1/1     Running   0          21h
kube-system      kube-scheduler-rkota-k8s-1            1/1     Running   0          21h
kube-system      weave-net-55xnf                       2/2     Running   0          21h
kube-system      weave-net-sv6cv                       2/2     Running   0          21h
redis-operator   redis-operator-78c558545b-7hs99       1/1     Running   0          21h
root@rkota-k8s-1:~/redis-operator/helm-charts# kubectl get pv
NAME           CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                                        STORAGECLASS    REASON   AGE
pv-operator1   1Gi        RWO            Retain           Available                                                local-storage            21h
pv-operator2   1Gi        RWO            Retain           Bound       redis-operator/redis-master-redis-master-1   local-storage            21h
pv-operator3   1Gi        RWO            Retain           Bound       redis-operator/redis-slave-redis-slave-1     local-storage            21h
pv-operator4   1Gi        RWO            Retain           Bound       redis-operator/redis-master-redis-master-2   local-storage            21h
pv-operator5   1Gi        RWO            Retain           Bound       redis-operator/redis-slave-redis-slave-0     local-storage            21h
pv-operator6   1Gi        RWO            Retain           Bound       redis-operator/redis-slave-redis-slave-2     local-storage            21h
pv-operator7   1Gi        RWO            Retain           Available                                                local-storage            21h
pv-operator8   1Gi        RWO            Retain           Bound       redis-operator/redis-master-redis-master-0   local-storage            21h

**Comment by iamabhishek-dubey** [comment] 2021-05-25 11:43
This is not a bug, it's the nature of Kubernetes Statefulsets. The PV will be released after you delete the PVC.

**Closed by iamabhishek-dubey** 2021-05-25 11:43 UTC
