### ISSUE TITLE
NodePort connection from outside

### ISSUE THREAD

**Issue by hreidar** [OT-CONTAINER-KIT/redis-operator#169] opened 2021-11-10 11:06 UTC
### Discussed in https://github.com/OT-CONTAINER-KIT/redis-operator/discussions/117

<div type='discussions-op-text'>

<sup>Originally posted by **MaiTest** July 25, 2021</sup>
Hello
i need to connect to my cluster from outside as im building it on a baremetal so i set the service type to NodePort and set a custom port to redirect 6379 to it.

But when i connect to the cluster and set any key it can't redirect to any slot on another node and give me connection time out error!
So, how to resolve that?  </div>

**Comment by iamabhishek-dubey** [comment] 2021-11-13 07:27
Can you please explain the steps which you have executed including the redis commands.

**Comment by hreidar** [comment] 2021-11-15 08:47
Hi, @iamabhishek-dubey, I just created this issue from the Discussions tab but the issue is that we are not able to access Redis from outside the k8s cluster even if we create a NodePort. I believe this is because the Redis cluster is redirecting my calls to another node in the cluster and the IP address is an internal ClusterIP so my call will not reach it and the request will timeout.

This issue only applies to a Redis cluster deployment for this reason.

**Comment by iamabhishek-dubey** [comment] 2021-11-29 08:14
use `redis-cli` with -c flag

**Comment by iamabhishek-dubey** [comment] 2021-11-29 08:14
you have to connect in cluster mode with redis, closing it because it's not a bug or enhancement

**Closed by iamabhishek-dubey** 2021-11-29 08:14 UTC
