### ISSUE TITLE
Upgrade from 0.11.2 to 0.12.0: Sigsegv

### ISSUE THREAD

**Issue by donch** [OT-CONTAINER-KIT/redis-operator#357] opened 2022-10-18 14:23 UTC
**What version of redis operator are you using?**

I upgraded redis-operator helm chart from v0.11.2 to v0.12.0

```shell
kubectl logs -f redis-operator-8488b858d6-zf5wk -n redis-system
{"level":"info","ts":1666102728.6338263,"logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1666102728.63444,"logger":"setup","msg":"starting manager"}
{"level":"info","ts":1666102728.6352816,"msg":"Starting server","kind":"health probe","addr":"[::]:8081"}
{"level":"info","ts":1666102728.6352818,"msg":"Starting server","path":"/metrics","kind":"metrics","addr":"[::]:8080"}
I1018 14:18:48.635933       1 leaderelection.go:248] attempting to acquire leader lease redis-system/6cab913b.redis.opstreelabs.in...
I1018 14:19:03.912294       1 leaderelection.go:258] successfully acquired lease redis-system/6cab913b.redis.opstreelabs.in
{"level":"info","ts":1666102743.9174802,"logger":"controller.redis","msg":"Starting EventSource","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"Redis","source":"kind source: *v1beta1.Redis"}
{"level":"info","ts":1666102743.917574,"logger":"controller.redis","msg":"Starting Controller","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"Redis"}
{"level":"info","ts":1666102743.917954,"logger":"controller.rediscluster","msg":"Starting EventSource","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"RedisCluster","source":"kind source: *v1beta1.RedisCluster"}
{"level":"info","ts":1666102743.9179826,"logger":"controller.rediscluster","msg":"Starting Controller","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"RedisCluster"}
{"level":"info","ts":1666102744.0185356,"logger":"controller.redis","msg":"Starting workers","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"Redis","worker count":1}
{"level":"info","ts":1666102744.0187,"logger":"controllers.Redis","msg":"Reconciling opstree redis controller","Request.Namespace":"redis-system","Request.Name":"test-redis"}
{"level":"info","ts":1666102744.0197392,"logger":"controller.rediscluster","msg":"Starting workers","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"RedisCluster","worker count":1}
{"level":"info","ts":1666102744.0248344,"logger":"controller_redis","msg":"Redis statefulset get action was successful","Request.StatefulSet.Namespace":"redis-system","Request.StatefulSet.Name":"test-redis"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1415795]

goroutine 253 [running]:
redis-operator/k8sutils.getProbeInfo(...)
	/workspace/k8sutils/statefulset.go:414
redis-operator/k8sutils.generateContainerDef({0xc000230816, 0x0}, {{0xc00077e140, 0x1c}, {0xc000230860, 0xc}, 0xc0008ae9c0, {0xc000900660, 0x22}, {0xc000230870, ...}, ...}, ...)
	/workspace/k8sutils/statefulset.go:291 +0x115
redis-operator/k8sutils.generateStatefulSetsDef({{0xc000230816, 0xa}, {0x0, 0x0}, {0xc000230840, 0xc}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	/workspace/k8sutils/statefulset.go:195 +0x1b6
redis-operator/k8sutils.CreateOrUpdateStateFul({_, _}, {{0xc000230816, 0xa}, {0x0, 0x0}, {0xc000230840, 0xc}, {0x0, 0x0}, ...}, ...)
	/workspace/k8sutils/statefulset.go:63 +0x18a
redis-operator/k8sutils.CreateStandaloneRedis(0xc000ba8000)
	/workspace/k8sutils/redis-standalone.go:40 +0x385
redis-operator/controllers.(*RedisReconciler).Reconcile(0xc0001c9770, {0xc00089abd0, 0x155e1a0}, {{{0xc000230840, 0x1668f60}, {0xc000230816, 0x30}}})
	/workspace/controllers/redis_controller.go:63 +0x29c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc000137130, {0x1942e58, 0xc00089abd0}, {{{0xc000230840, 0x1668f60}, {0xc000230816, 0x413a94}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000137130, {0x1942db0, 0xc000868480}, {0x15b3980, 0xc00003a5e0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000137130, {0x1942db0, 0xc000868480})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:223 +0x357
```

redis-operator version: 0.12.0

**Does this issue reproduce with the latest release?**

Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.12-dispatcher-dirty", GitCommit:"fde00375407ad0afadd681a3505054ec83f935ec", GitTreeState:"dirty", BuildDate:"2022-07-19T18:58:44Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:23:01Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

**What did you expect to see?**

The operator running properly.

**What did you see instead?**

The operator is in CrashLoopBackOff state

**Comment by donch** [comment] 2022-10-18 14:38
Here is a Redis standalone deployed : 

```
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: test-redis
  labels:
    monitored: "true"
spec:
  redisExporter:
    enabled: true
    image: "quay.io/opstree/redis-exporter:1.0"
    imagePullPolicy: "IfNotPresent"
    resources:
      limits:
        cpu: 10m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
  kubernetesConfig:
    image: "quay.io/opstree/redis:v6.2.5"
    imagePullPolicy: "IfNotPresent"
    resources:
      {}
  redisConfig: {}
```

And the install command used : 

`helm upgrade redis-operator ot-helm/redis-operator --install -n redis-system --version 0.12.0`

**Comment by iamabhishek-dubey** [comment] 2022-10-18 16:54
Looks like your upgrade didn't work successfully, I tested the same manifest against v0.12.0, and I can see it's working.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/26764731/196493915-31e248e4-c696-40b1-94ac-7d0175c6eed4.png">


The issue is with `helm upgrade` because it doesn't upgrade the CRD, and we made some changes in the CRD version of redis-operator.

One way to fix this would be to upgrade CRD manually or remove and install the operator since it's a helm limitation 😄 .

Closing this issue for now. Please feel free to reopen it if you find anything interesting.

**Closed by iamabhishek-dubey** 2022-10-18 16:54 UTC
Labels: bug
