### ISSUE TITLE
Connect sentinel but can not get master info

### ISSUE THREAD

**Issue by xuziheng1002** [OT-CONTAINER-KIT/redis-operator#475] opened 2023-03-30 04:52 UTC
I setup the sentinel cluster and replication cluster, and checked that master info is collected by sentinel by following command:
```
127.0.0.1:26379> SENTINEL get-master-addr-by-name sss
1) "172.31.5.40"
2) "6379"
```
but it was always get error `redis.sentinel.MasterNotFoundError: No master found for sss`
when I run this python in k8s cluster:
```python
import redis
sentinel = redis.sentinel.Sentinel([('rs1-sentinel', 26379)], socket_timeout=2000)
sentinel.master_for('sss', socket_timeout=2000)
```

how can I solve this problem?

following is my config of redis-sentinel:
```
redisSentinel:
  clusterSize: 3
  image: quay.io/opstree/redis-sentinel
  tag: v7.0.7
  imagePullPolicy: IfNotPresent
  redisSecret:
    secretName: redis-secret
    secretKey: password
  serviceType: ClusterIP
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
redisSentinelConfig:
  redisReplicationName: "rr1"
  masterGroupName: "sss"
externalService:
  enabled: true
  serviceType: NodePort
  port: 26379
serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  namespace: monitoring
redisExporter:
  enabled: true
  image: 10.20.1.250/prd/redis-exporter
  tag: "v1.44.0"
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
sidecars: []
nodeSelector: {}
storageSpec:
  volumeClaimTemplate:
    spec:
      storageClassName: aliyun-nfs-performance
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: 1Gi
securityContext:
  runAsUser: 1000
  fsGroup: 1000
affinity: {}
```

and this is config of redis-replication:
```
redisReplication:
  clusterSize: 3
  image: quay.io/opstree/redis
  tag: v7.0.5
  imagePullPolicy: IfNotPresent
  redisSecret:
    secretName: redis-secret
    secretKey: password
  serviceType: NodePort #ClusterIP
  resources:
    requests:
      cpu: 500m
      memory: 4Gi
    limits:
      cpu: 2000m
externalConfig:
  enabled: true
  data: |
    databases 64
    maxmemory 12gb
    maxmemory-policy noeviction
    maxclients 1000
externalService:
  enabled: true
  annotations:
    foo: bar
  serviceType: NodePort
  port: 6379
serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  namespace: monitoring
redisExporter:
  enabled: true
  image: 10.20.1.250/prd/redis-exporter
  tag: "v1.44.0"
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
sidecars: []
storageSpec:
  volumeClaimTemplate:
    spec:
      storageClassName: aliyun-nfs-performance
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: 1Gi
securityContext:
  runAsUser: 1000
  fsGroup: 1000
affinity: {}
```

**Comment by iamabhishek-dubey** [comment] 2023-03-31 08:34
Can you try using the sentinel's FQDN URL or the script in the same namespace? This looks more like the issue is how you connect to redis sentinel. 

Closing this issue since it is not an actual issue or bug. Please reopen if required.

**Closed by iamabhishek-dubey** 2023-03-31 08:34 UTC
